### ISSUE TITLE
Cannot set LEDs to Solid State

### ISSUE THREAD

**Issue by jetpham** [4201VitruvianBots/RapidReact2022#14]
Cannot set all of the LEDs to solid. THe closest attempts were
using setLEDs() in the LED subsystem, but that has a limit of 255 less which is actually closer to 130 less

Other animation types even with 0 speed do not recreate the desired effect.

The Zero-LED branch has code that cycles through every animation type

**Comment by j12bates** [comment]
update or no

**Comment by jetpham** [comment]
It's fixed
